### ISSUE TITLE
I have problem on my Windows 10 computer!

### ISSUE THREAD

**Issue by zivoradmilekic** [sunOpar/react-component-maker#1]
It can not run ES6 code. My node version is 4.4.7 and npm version is 3.10.6
Maybe you should ES6?!
```
$ mkreact Test
C:\Users\**************\AppData\Roaming\npm\node_modules\react-component-maker\bin\mkreact.js:28
    let val = process.argv[2].split(',')
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

```

**Comment by sunopar** [comment]
v1.2.2 fixed.
